### ISSUE TITLE
Geez title in ATs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#1]
The AT guidelines state:

> For the title of the work, when possible: a) include most common definition in British English; b) include Ge'ez title; c) consider including alternative titles used in principal art projects (e.g. ICONCLASS, Artstor, Index of Christian Art).
(http://betamasaheft.eu/Guidelines/?id=artThemes)

and the example given (AT1005Crucifixion) includes a Geez title. However, this title is no longer present in the record, and I found no other Geez titles in the AT records. Are the guidelines still up to date?

**Comment by Gnisci** [comment]
Dear Thea,

Thanks for raising this point. Initially, I thought it would be beneficial to include (when possible) the Ge'ez title for the ATs. I later became preoccupied about consistency (not sure it is possible to give a specific  Ge'ez title for all the ATs), so I decided it was to put the matter on hold and first finish providing a complete list of ATs with abstract and bibliography and then (if it was deemed worthy and necessary) add the Ge'ez titles in a second moment.

What are your thoughts on this matter?

Thanks

**Comment by PietroLiuzzo** [comment]
I would live the guidelines as they are and let people do the best they can if they follow the guidelines. we do not require those titles to have a complete and functioning record, but they can be added with time, so it can stay as the possibilistic formulation in the guidelines is also fine IMHO. can I close?

**Comment by Gnisci** [comment]
I second Pietro's suggestion, it would be nice to have the titles in the future, though at present I would prioritize other tasks.

**Comment by thea-m** [comment]
Good, then we'll leave the guidelines as they are, but I will still change the example to reflect the actual record.
