### ISSUE TITLE
narrative units (in additions)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#37]
There are currently only three occurences of a narrative unit in our manuscript descriptions, all of them in additions and none encoded as described in the guidelines, where we have:

> If the type of document is known, then there should be a narrative entity to which a @ref can be given.
> 
> 
>                     <item xml:id="a2" xml:lang="am" ref="NAR0001gwǝlt">
>                         <locus target="#3v"></locus>
>                         <p>Land donation (gwǝlt) of <persName ref="PRS8344sahlaDe">Śāhlā Dǝngǝl</persName> (A.D. 1832-40, and again 1841-55) to the priests of <placeName ref="LOC2550Darasg">Darasge</placeName>, in Amharic. </p>
>                     </item>

This example is no longer encoded with a narrative unit but with `<desc type="LandGrant">`, which is what I would have done as well.

If narrative units should continue to be used here, it might be useful to specify their definition in the guidelines and to clarify their distinction from "types" of additions. A narrative unit does not have a fixed sequence and content, but does this mean that it is identical with a genre or addition type? 

(This use is different to that of narrative units as "text portions (paragraphs, chapters, miracles, etc.) which are extant as different versions in multiple recensions of the same work or even in different works")

**Comment by PietroLiuzzo** [comment]
on further digging, the <title> in <desc> was indeed the option chosen AND documented in the guidelines in additionsVaria. So in this commit https://github.com/BetaMasaheft/Manuscripts/commit/949773e41cc857f19762dd9e424270ac32d25e71 I have partially reverted some changes I introduced yesterday, not to introduce the use of `@corresp` but stick to simple title

**Comment by eu-genia** [comment]
which is the solution to my question above, to "level out" the status of land grants transmitted as `msItems `with 
`<title type="complete" ref="NAR0001gwelt">Land donation by <persName ref="PRS10626ZaraY"/>`
and as
additions with currently
`<desc type="LandGrant">Gwǝlt of <persName ref="PRS3874eskender">ʾƎskǝndǝr, Constantine</persName> (<date>A.D. 1478-1494</date>) </desc>`?
Should one also add a `@corresp ` (in `item`) or `@ref` (in `title`) to `NAR0001gwelt `for `additions`, so that when I search for all narrative units of gwelt type I can find them all?

**Comment by PietroLiuzzo** [comment]
In the commits above as you have seen I have tried to simplify the options, removing the `@corresp` in data and guidelines to stick only to `title[@ref]` in both `msItem`s and `additions//item`s for both Textual and Narrative units.
- [ ] I will actually add also an example from BDLbruce93, as it shows well that Narrative units, being not sequence bound, can be used like here for several land donations. 
Given that the association to a Narrative unit should be a different thing compared to assigning a type, there are two ways you can find both together. The simplest I would say would be to add the `<title type="complete" ref="NAR0001gwelt"/>` in BLorient481 or other mss where you have texts which are similar in `additions//items`. You should also be able to additionally add a keyword LandGrant to NAR0001gwelt (only), but it looks like these values of the taxonomy did not make it to the allowed values for a keyword in the schema, but only as valid values for desc. I now do not recall the rationale, I have to investigate a bit unless somebody else remembers. Third option is of course a relation between `msItem`s ID and keyword but I would think it is suboptimal in this case. A loose relation (skos:broadMatch perhaps) between Narrative unit and keyword (again, once) would allow to display in the Narrative unit page both things, and is perhaps the speediest and I can try it now while I complete the two tasks above

**Comment by PietroLiuzzo** [comment]
from the latest commit, the narrative units also have a block on the rights, similarly to works, listing where they are used in manuscripts.
see https://betamasaheft.eu/narratives/NAR0001gwelt/main
here (expand the box to a dialogue by clicking the title) you can see a list of all instances of this unit used as main or additional content AND, separately, a list of where the keyword associated with it in the relation element is used. please @eu-genia let me know if this is ok. You can in this way get the together results, without mixing stuff in other searches.

This means also that a narrative unit can be associated to a number of different keywords (will be listed separately). 

- [ ] I will add this to the GL as well, but discourage its use for works as well.

Also work records now show in the list separately occurrences in main contents or additions, 
e.g. https://betamasaheft.eu/works/LIT2861RepCh142/main

similarly do the comparison function, which will summarize also contents in additions, e.g.
https://betamasaheft.eu/compare?workid=LIT2861RepCh142
