### ISSUE TITLE
punctuation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#48]
a paragraph on the encoding of punctuation would be useful

**Comment by PietroLiuzzo** [comment]
And what should it contain?

**Comment by thea-m** [comment]
either a confirmation of the encoding of punctuation present in Ethiospare manuscripts (which is nowhere present in the guidelines and unsurprisingly was not used in any other records)
```
  <layout>
                           <ab type="punctuation" subtype="Executed">regularly</ab>
                           <ab type="punctuation" subtype="Usage">logical</ab>
                           <ab type="punctuation">
                              <list>
                                 <item xml:id="div1"> I. colon.</item>
                                 <item xml:id="div2"> II. nine dot asterisk; </item>
...
```
or, if for some reason that is not considered ideal anymore, an alternative

**Comment by PietroLiuzzo** [comment]
So it would be about encoding general features of the punctuation in the manuscript. I am not sure this was done extensively in ES either and if it was not, I would avoid extending to rule a limited usage praxis. @DenisNosnitsin1970 @eu-genia could you confirm please if this needs to be documented to be used also in other manuscripts or if it was only done for a limit number of cases and can be thus rediscussed?

**Comment by DenisNosnitsin1970** [comment]
It was not done extensively in Ethio-Spare, as the operation was found very time consuming and leading 
to a level of details that was not really desired. It can be rediscussed, though, but it is applicale only to the cases where the text is really accessible. 
Here below is the range of punctuation signs that was set up (examples are needed to be added):

Punctuation: 
Cp. UhlPal 89-94, 204f.; Dillmann, Grammar..., 32f.; Conti Rossini Grammatica elementare...,  9 etc.).
I. Word dividers:
1. Colon፡ (näṭǝb)
2. Four dot asterisk/ Double colon ።  (näqwet/ arat näṭǝb)
3. Short line with dots above and below (Comma 1) [= obelus]: ፥ (säräz)
4. Colon with dashes above and below (Comma 2 / Enumeration sign 1): ፤
5. Colon with dash above (Comma 3): ፣ 
6. Five red and black dot colon (Comma 4/ Enumeration sign 2):
7. Three dot vertical colon: ፧ 
8. Colon of two black dots and three red dashes (in-between, above, below)
9. Quotation sign 

 II./III. Sentence and Section / Text dividers 
1. Four dot asterisk / Double colon (näqwet/ arat näṭǝb) ።
2. Five dot asterisks 
3. Nine dot asterisk ፨
4a. Doubled nine dot asterisks, with/without dashes in between (mǝˁǝraf): ፨፨, 
፨ = =  ፨
4b. Doubled nine dot asterisk, with two lines in between ፨ ===  ፨
4c. (Three and more) nine dot asterisks: ፨ ፨ ፨ ፨ ፨
4d. (More than two) nine dot asterisks, connected with dashes: ፨ = =  ፨ = =  ፨ = =  ፨ = =  ፨ = =  ፨
5a. Doubled four dot asterisks, with/ without dashes in between (mǝˁǝraf): ።።,  ። = = ።
5b. Three and more four dot asterisks ። ። ። ። ። ።
5c. More than two four dot asterisks, connected with dashes:
:: = = :: = = :: = = :: 
5d. More than two four dot asterisks, connected with lines
6. “Reference mark”: ፠ 
7. The paragraph sign on the left of a text column, accompanying sentence divider:  ፦
8. Chi Rho 
9. Crux ansata 
10. Coronis (together with or separated from Crux ansata)
11. Chain of black dots .................
12. Chain of black and red dots ..........................
13. Chain of black right-pointing chevrons >>>>>>>>>>>
14.  Chain of black and red right-pointing chevrons >>>>>>>>>>>
15. Ornamental bars
16. Nine dot asterisks and chains of (black / red) dots in between:            ፨  ፨  ፨
17. Nine dot asterisks and chains of black and red right-pointing chevrons in between:   ፨ >>>>>> ፨ >>>>>> ፨ >>>>>>>፨
18. X-shape sign (with dashes above and below) (MQM-002).

Others:
18. Long black lines 
19. Long red lines 
20. Long black and red lines      
21.  Chain of red and black dashes ---------------------
22. Black and red dots and dashes
23. Black dots and short dashes
24. “X” with dashes above and below
25. Black line with one (or more) chain of red and black dots in the middle
26. Chain of coronis signs, under the chain of nine dot asterisks with thin red and black lines in between (fols. 49r, 182vb)
Rubricated X sign with shevron on the right: x>
Etc.

**Comment by thea-m** [comment]
Thank you, @DenisNosnitsin1970 
Including a paragraph on the possibility of punctuation encoding obviously does not prescribe to encode all punctuation everywhere from now on.

**Comment by DenisNosnitsin1970** [comment]
Not really, but some features more important for dating/typologies can be picked up.

**Comment by DenisNosnitsin1970** [comment]
Some less important can be indeed facultative.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 I agree, that why a little elaboration and systematisation would be useful.

**Comment by thea-m** [comment]
Do we agree that
- we want to keep the possibility of encoding information on punctuation
- this can be done with the current practice in the converted ES manuscripts of having in `<layout>`  a `<ab type="punctuation">` with a `<list>` containing single items for the punctuation signs used in the manuscript ?

Then I could start by adding this with an example and @DenisNosnitsin1970 's helpful list to the guidelines. I think that for now, that would already be an improvement and can serve as a starting point if someone feels the need for more elaborate encoding.

(It might be already useful to have separate lists for word and sentence/section dividers.)

@DenisNosnitsin1970 @eu-genia @DariaElagina @sologebre @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
Thanks @thea-m, yes, please use the ES as example. I would also copy over and enphasise your statement above about the fact that this is only to be done when one has a really strong feeling about it. perhaps also copy over the statement from @DenisNosnitsin1970 comment above (time consuming, etc.)

**Comment by thea-m** [comment]
a new issue can be opened when someone wants to develop the encoding of punctuation more
