### ISSUE TITLE
relation between Art Theme and its content

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#49]
just to clarify: is saws:contains the right relation between an Art Theme record and the persons depicted in it? As in AT1003Arrest: 
`<relation name="saws:contains"  active="AT1003Arrest" passive="PRS5684JesusCh">`
I had used ecrm:P129_is_about for the same purpose (having mentally reserved saws:contains for work records), so maybe others might also be confused and it would be good to put it in the guidelines.
@PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
please add examples and clarification in the guidelines where you think it is appropriate, I also think it is a good idea.

**Comment by thea-m** [comment]
thank you!
