### ISSUE TITLE
choice corr sic and @resp

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/guidelines#56]
we need to add an example of the use of choice[corr[@resp]][sic] 

this is supported by the stylesheets which render the clickable option, and it is clear that the correction has a author.

````xml 
<choice resp="PL">
<sic>ወ</sic>
<corr>መ</corr>
</choice>
````

should be deprecated as it does not tell what is the `@resp` as far as I can say

there are additionally 90 cases so far which need to be fixed 
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3Achoice%5B%40resp%5D

An example should be added to an appropriate page of the following kind

````xml 
<choice>
<sic>ወ</sic>
<corr  resp="PL">መ</corr>
</choice>
````

this is very often correctly used 
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3Achoice%5Bt%3Acorr%5B%40resp%5D%5D

**Comment by PietroLiuzzo** [comment]
@thea-m @AngelaMueller @eu-genia @sologebre @DariaElagina @DenisNosnitsin1970  any volunteers?

**Comment by thea-m** [comment]
I will correct my records and add the example to the guidelines, but I think that it would be better if @AngelaMueller would correct the MM records, since she is working with them currently and familiar with the text genesis

**Comment by PietroLiuzzo** [comment]
we still have to clarify those cases anyway https://github.com/BetaMasaheft/Documentation/issues/1174 
thanks!

**Comment by thea-m** [comment]
I am about to fix these records as I promised to do, but I must say that to me it is now self-evident that a `@resp` in `<choice>` refers to both child elements, i.e. both the identification of the mistake and the providing of its correction. But as I am probably behind most of these instances, it might be an (albeit time saving) idiosyncrasy of me. @PietroLiuzzo if you confirm that it is an idiosyncrasy I will go ahead with the fixes.

**Comment by PietroLiuzzo** [comment]
well, if we do not need fixing and can do with a clarification in the GL, let us do so! your phrasing here seems very suitable to me. I will add support for the `@resp` on `<choice>` accordingly
