### ISSUE TITLE
element <seg> is not allowed here

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/guidelines#68]
Ciao Pietro,
I was trying to find a sequence in which the schema would allow me this, but I failed.
Could you please help me? All the examples I checked are not validated, I wonder whether the guidlines advise us what is proper for this
`<qxml:lang="gez">   
                 <seg ana="#invocation" type="interpretation">` 
Grazie!

**Comment by PietroLiuzzo** [comment]
Please, try clarify your issues.

- on which branch are you and which file are you editing? 
- what is that you are trying to do?
- what have you tried ?
- if ref to guidelines, which page (link, please)?
- if you get an error, which error do you get?
- can I see the error in the latest commit to that branch? if not how do I reproduce it?

**Comment by PietroLiuzzo** [comment]
in your example, please add a space between element name and attribute name

> <q xml:lang

not 

> <qxml:lang

<seg> is allowed by BM schema inside <q> and

**Comment by nafisa-valieva** [comment]
Ciao Pietro, yes, my example was modified, your example is correct, but it does not help.
<seg> is allowed by BM schema inside <q>, but I was trying to find a position in which <seg> is allowed by BM schema inside <q> would be allowed and I can not find it. I tried to use various examples offered for Text Encoding in the guidelines, `<ab>` seems  not to allow it or there is something else which escapes my attention

my present attempt is the following:
<img width="769" alt="troubles" src="https://user-images.githubusercontent.com/28699981/69623272-da070300-1042-11ea-8b3a-0f7c914a5310.PNG">

**Comment by PietroLiuzzo** [comment]
but you did not answer my questions, so, I am still stuck with only some clues... a precise question would have allowed a precise and quick answer. These changes are not committed to Nafisa_GG, so I cannot see them. Please commit the changes you made to a branch, Nafisa_GG or any other you are working an, so that I can look at them and figure out what the problem is.

**Comment by nafisa-valieva** [comment]
yes! now you have it in Nafisa_GG, "for Pietro"

**Comment by nafisa-valieva** [comment]
on which branch are you and which file are you editing?
what is that you are trying to do?
what have you tried? - I have tried to find a possible position for `<q> with <seg>`
if ref to guidelines, which page (link, please)?
example 1 [https://betamasaheft.eu/Guidelines/?id=corpora,] incorporate in 
 [(https://betamasaheft.eu/Guidelines/?id=text-encoding)]
or in [(https://betamasaheft.eu/Guidelines/?id=Documents)]
or in [(https://betamasaheft.eu/Guidelines/?id=additionsVaria)]

if you get an error, which error do you get? liner error, element `seg` is not allowed here
can I see the error in the latest commit to that branch? if not how do I reproduce it? you can see this error, but I marked it as `<!-- -->` to make the file valid.

**Comment by PietroLiuzzo** [comment]
This was an error in the schema. the above commit should fix this. the validation reported the error on the type, which is now not anymore matched in the test for that rule. However, the reported error is not the one you were getting. please close atom, reopen and test the validation again. it could be that the schema is cached in its previous version and it takes a bit for Atom to realize  a new version is available.

**Comment by nafisa-valieva** [comment]
It works, grazie, Pietro!

**Comment by PietroLiuzzo** [comment]
then close the issue!

**Comment by nafisa-valieva** [comment]
ciao!

**Comment by PietroLiuzzo** [comment]
thanks! a closed issue is a wonderful gift!
