### ISSUE TITLE
visual overlapping

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#74]
On my laptop, there is some overlapping between the main page and search results on the relation element page https://betamasaheft.eu/Guidelines/?q=relation&id=relation

![image](https://user-images.githubusercontent.com/19650382/72278510-13fc8a80-362c-11ea-8155-a12c41b2173c.png)

It's not dramatic, but would be more pleasing otherwise :)

**Comment by PietroLiuzzo** [comment]
Thank you @thea-m , could you have a look again and tell me if it is better now?

**Comment by thea-m** [comment]
perfect now!
