### ISSUE TITLE
elaborate collation guidelines

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#75]
I think it would be very helpful and user-friendly if the collation guidelines would be a little bit more elaborated, not regarding the encoding as much as the description of collation itself (What I mean, in a few words, what the used formulas for stubs, added leaves etc. mean and how to use them. It is possible to figure most of it out, but it would be nice if there were a place where it would be described in more detail, for example for someone working for the first time with describing collation). I believe that @DenisNosnitsin1970, you know the most about it? Would you agree to develop this guidelines section a bit (obviously only if you agree that it would be helpful :) )

**Comment by DenisNosnitsin1970** [comment]
Yes, I'll do this.

**Comment by thea-m** [comment]
wonderful, thank you!

**Comment by DenisNosnitsin1970** [comment]
The <note/> included into the collation <item/> 
in the way it is indicated in the current guidelines, 
like here (example 5 of the Guidelines, "Collation")
<item xml:id="q22" n="22">
<dim unit="leaf">3</dim>
 <note>A folio stub is visible between 
ff. 175 and 176. F. 176 is cut off about 
midway between gutter and fore edge. </note>
  2, stub after 1
</item>
will not be visualized and remains invisible for the user. 
Can anything be done about this?
The same is valid for <num value="20">፳</num> (example 6 of the Guidelines, "Collation").

**Comment by DenisNosnitsin1970** [comment]
The same again, for the sake of clarity.
[Collation problem.docx](https://github.com/BetaMasaheft/guidelines/files/4232026/Collation.problem.docx)

**Comment by thea-m** [comment]
@PietroLiuzzo can you help regarding the last comment by @DenisNosnitsin1970 ? I remember darkly that  the `<note>` inside the `<item>` was added to the guidelines by EMIP requirement.. But if @DenisNosnitsin1970 has found this to be the only place to encode certain information, its visualisation (and the kind of information encoded there) might need to be rediscussed.

**Comment by PietroLiuzzo** [comment]
yes I will look at this issue and document now.

**Comment by thea-m** [comment]
Thank you! Since I am working on the collation guidelines now: Including general information on a quire in the respective `<item>` seems to be an important need, for which there are conflicting hints in the guidelines and elsewhere. There is the `<note>` after `<locus>` mentioned here (not visualised currently), and in Denis' document also mentions the same place for encoding this information, but without the `<note>` element.

**Comment by DenisNosnitsin1970** [comment]
Dorothea, 
the updated document is in my computer in the office, unfortunately. I was waiting for Pietro's response/comment.

**Comment by thea-m** [comment]
I think there is already much valuable clarification and structure in the document that I have. The aim is for the page to be more informative than it currently is, there will always be ample room for later perfection. It would be good, I think, to take it out of the famous document and into a more general discussion.

**Comment by DenisNosnitsin1970** [comment]
Still, it is better to use the updated document. It really drifted far from the version you have. I will get the right document by the next week - the nearest future.

**Comment by thea-m** [comment]
Well, now I already did it. I will make a branch in the guidelines repo and then we can at least edit there.

**Comment by PietroLiuzzo** [comment]
I am a bit at odds with the doc and the comments. I am looking now at the visualization of this elements and will report back asap when I have found the origin of the issue in question. in general, it should make no difference whatsoever where note is used, since it is valid there. I would stick with what is in the guidelines first, and find the source of the "elsewhere" to make it consistent to the guidelines  before changing the encoding. This we can do also in absence of the document from @DenisNosnitsin1970 I believe.

**Comment by PietroLiuzzo** [comment]
I don't think the document I have from the comment up here is the one with the valuable clarification, alas... I only have 92 words more or less similar to the comment above... could some one email me the correct document? thanks a lot!

**Comment by DenisNosnitsin1970** [comment]
Pietro, in this document I reported the problem that I noticed experimenting with collation. It clarifies nothing, it only report the problem. Dorothea and myself meant another document (at least I assume this)

**Comment by PietroLiuzzo** [comment]
Yes, thanks @DenisNosnitsin1970 , now Dorothea draw my attention to this other document, which she had sent in another email. I should have collected all material now...

**Comment by PietroLiuzzo** [comment]
I don't have all, please @thea-m could share the name of the gl branch you are working on? thanks!

**Comment by thea-m** [comment]
collation, I just committed it. I think I will stop working there now before we have complete chaos

**Comment by DenisNosnitsin1970** [comment]
In that bigger document there is nothing constructive concerning the problem. I took over the older guidelines, but I discovered that this specific feature does not work. I did not change anythig as I was waiting as to what kind of solution would be found.

**Comment by PietroLiuzzo** [comment]
sorry, the caos is due to me chiming in here late and trying to go through the issue of the visualization before that of the guidelines. sorry about this, I should have followed better from the begining. please be patient, I am on this and will be back soon with news. thanks a lot!

**Comment by DenisNosnitsin1970** [comment]
No problem, have your time!

**Comment by thea-m** [comment]
No need to apologise :) What was relevant here now was the visualisation issue, separate from the larger guideline issue that Denis has already worked on. How shall we proceed now? Shall I continue on the branch (what was still missing from my point of view before submitting these edits to general feedback is mainly the integration of examples) or would that be pointless @DenisNosnitsin1970 ?
There is no need for any urgency whatsoever.

**Comment by DenisNosnitsin1970** [comment]
I would say, if to have the updated material is essentual for what you are doing, then you would rather wait a little, I will get it in the next days (I myself have to run through it at least once, as I put it aside a month ago). On Monday we will be able to continue.

**Comment by PietroLiuzzo** [comment]
for the visualization issue, I am working on a solution which will not impact guidelines at all, so you can procede with no problem on your task, actually, what a nice thing that we can work on different things at different times and only need to let everyone else know :)

**Comment by PietroLiuzzo** [comment]
if you look at https://betamasaheft.eu/manuscripts/BLorient718/main, one of the two examples I found with both num and note, you will see how they are rendered now.

**Comment by PietroLiuzzo** [comment]
eventually the example in the guidelines seems to not exist any more in the data, but that is fine I think.

**Comment by DenisNosnitsin1970** [comment]
Do you mean that <note> inserted in the item xml:id="q" will now be visualized in such a way?

From the point of view of the arrangement of this information, "Quire Numeration": should be above "Notes" and render "q" followed (or, if technically possible, "n" value) followed by the Ethiopic quire number. "Notes" should below.

**Comment by DenisNosnitsin1970** [comment]
"Notes" should be below.

**Comment by PietroLiuzzo** [comment]
I don't mean it, it is so :) but as it has changed it can always be changed otherwise, just let me know, visualization is ephemeral. 
The or / if part is not clear to me, I have tried my best to parse it, and you can check the same example above.
Just for the record let us try not to make the view influence the encoding in the guidelines in any way.

**Comment by PietroLiuzzo** [comment]
for example I am not clear about below what, below the diagram, below the numeration? just le me know.

**Comment by DenisNosnitsin1970** [comment]
Yes, in Orient718  I see exactly what I meant. Is any difference is produced by the position of the <note>? For the encoder, it would be logical to place it as the last before <item> is closed.

**Comment by DenisNosnitsin1970** [comment]
(In most of the cases, there will be, of course, no information to put in the note).

**Comment by PietroLiuzzo** [comment]
that is fine, yes, the element can be placed where you want, and you should be able to have more than one, in which case you will have Notes: 1)..... 2) .....

**Comment by PietroLiuzzo** [comment]
In the branch collation, the first thing I am noticing is that the phrasing has been changed to a more generic one. for example I find the current formulation of the first introductory sentence much more clear.

**Comment by DenisNosnitsin1970** [comment]
Sorry, I do not know what you are reading. If you got smth from Dorothea, it has been surpassed.

**Comment by PietroLiuzzo** [comment]
also the textblock concept is used only here and in binding description, and has no corresponding thing in TEI. 
I am looking at the "emergency commit" which is the same of the document I got via email.
do we perhaps want to collaboratively edit this  e.g. in g docs before we put it into the collation branch?

**Comment by DenisNosnitsin1970** [comment]
Sure, but, as I explain above, I will procure the updated version.

**Comment by PietroLiuzzo** [comment]
no worries! at least we have now the view of all what should be viewed. :) thanks!

**Comment by thea-m** [comment]
I believe there is no need for my contribution to this anymore, just let me know if you want me to bring this emergency commit to a state where it contains complete sentences and examples or not. I will not do anything on this for the time being.

**Comment by thea-m** [comment]
I believe that the visualisation issues discussed in the middle of the issue have been solved? Please reopen if not
