### ISSUE TITLE
improve detail of description of use of relations

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/guidelines#77]
as for https://github.com/BetaMasaheft/Documentation/issues/1307

relations and the schema need to be updated to provide better support on how to use

**Comment by PietroLiuzzo** [comment]
I have merged this already to facilitate checking in the app, and request your opinion on the way I have set it up. beside all the open points in the issue above, I would like to add short definitions everywhere and add in the schema a link to each of these where available. @thea-m @eu-genia @sologebre @DenisNosnitsin1970 @DariaElagina

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/Guidelines/?id=relations

**Comment by thea-m** [comment]
Thank you Pietro for all the work! I think that the guidelines page is now very helpful. We need to work on the short definitions in the schema. I would also include there the type of entities' relations for which this relation can be used, as this was what let to most of our problems.
Were you planning to add the definitions in the guidelines or the schema?

**Comment by PietroLiuzzo** [comment]
in the schema, the guidelines page will reflect that [here](https://betamasaheft.eu/Guidelines/?id=relation)

**Comment by PietroLiuzzo** [comment]
thanks!

**Comment by PietroLiuzzo** [comment]
should I go on and add the person/person, work/manuscript in each?

**Comment by thea-m** [comment]
That would be great

**Comment by PietroLiuzzo** [comment]
if you check the above pages I have reordered and tidied up again the list adding at the beginning of each description something like @active : Entity, @passive : Entity 
the order of the entries is also the same as in the descriptive page of the guidelines, to the extent to which this is possible (the descriptive page splits and repeats, the schema cannot, it needs to go statement by statement) I have taken the liberty of completing the matching to the syriaca properties as well, adding died-at and commemoration.
