### ISSUE TITLE
ontology page

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#80]
There seems to be no content on https://betamasaheft.eu/Guidelines/?id=ontologyView
![image](https://user-images.githubusercontent.com/19650382/75977485-cccca080-5edc-11ea-88f0-f96476cdad4e.png)
The first link https://betamasaheft.github.io/RDF/ leads to a 404 file not found

**Comment by PietroLiuzzo** [comment]
you are right. this cannot work anymore, because it is calling a http service.... I will have to find an option.
