### ISSUE TITLE
code in guidelines

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#84]
Could you - if it is in any way relevant - maybe add here https://betamasaheft.eu/Guidelines/?id=editingGuidelines when to use `<code>` in the encoding of the guidelines? I saw you used it for the names of relations, where I would have used `<val>`. Thank you!

**Comment by PietroLiuzzo** [comment]
I do not think I have been any consistent... but I will have a look

**Comment by PietroLiuzzo** [comment]
ich war eigentlich konsequent :) habe ich eine ziele hinzugefugt für dieses und für lawd:hasAttestation
