### ISSUE TITLE
"main" in @type for persName

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#85]
The value main is not included in the schema for @type in `<persName>`, despite being mentioned in the guidelines (https://betamasaheft.eu/Guidelines/?id=persons). I'm not sure whether this is an accident or I (and the guidelines) missed a discussion on this. I only found this old issue: https://github.com/BetaMasaheft/Documentation/issues/868
should I just update the schema?

**Comment by PietroLiuzzo** [comment]
added

**Comment by thea-m** [comment]
Thank you!
